import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={inter.className}>
        <Navbar />
        <main>{children}</main>
        <footer className="bg-gray-800 text-white py-12">
          {/* Footer content will go here */}
          <div className="container mx-auto px-4">
            <p className="text-center">© 2025 BravArt. Toate drepturile rezervate.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
